name: Test a reusable workflow and an action with inputs and outputs 
on:
  workflow_dispatch
env:
  pt:
    # workflows-and-actions/reusable-workflows-and-actions
    ${{vars.REUSABLEWORKFLOWSANDACTIONS_PATH}}/.github/workflows/inputs_and_outputs.yml@main
jobs:   
  job0:
    runs-on: ubuntu-latest
    steps:
      name: test var
        echo     ${{vars.REUSABLEWORKFLOWSANDACTIONS_PATH}}/.github/workflows/inputs_and_outputs.yml@main
  job1: 
    name: j1 call reusable workflow
    uses: ${{env.pt}}
    with:
     input1: an_input
  job2:
    name: j2 use output from j1
    runs-on: ubuntu-latest
    needs: job1 # start only if job1 is complete
    steps:
      - name: use output from a completed job
        run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}  
  job3:
    name: j3 call an action and use output
    runs-on: ubuntu-latest
    steps:
      - name: call an action in this step and use the output in the next step.
        id: get_output        
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/inputs_and_outputs@main
        with:
         input1: another_input
      - name: use output from previous step
        run: echo ${{ steps.get_output.outputs.firstword }} ${{ steps.get_output.outputs.secondword }}          
  job4:
    name: j4 pass output between steps of a job
    runs-on: ubuntu-latest
    steps:
      - name: create output
        id: get_output
        run: echo "output3=myoutput" >> $GITHUB_OUTPUT 
      - name: use output from previous step
        run: |
         echo ${{steps.get_output.outputs.output3}}
         echo test done
      
      
  
         
