name: Test a reusable workflow and an action to read and write files 
on:
  workflow_dispatch
jobs:   
  job1: 
    name: read file
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/read_write_files.yml@main
    with:
      json_file_path: .github/test-files/f1.json
      yaml_file_path: .github/test-files/f1.yml
  job2: 
    name: read output from previous step
    runs-on: ubuntu-latest
    needs: job1
    env:
      jsondata: ${{needs.job1.steps.read_json.outputs.result}}
    steps:
      - name: log output
      # if: ${{ env.jsondata == 'newtest' }} # we must accesss env vars using env context when outside a run
        run: | 
          echo ${{env.jsondata}}
          echo ${{env.jsondata.level0.level1.level2.level3.level4.list}}
      #  echo yamldata=${{steps.read_yaml.outputs.result}} >> GITHUB_ENV
      #  echo ${{yamldata.level0.level1.level2.level3.level4.list}}
      
      
  
         
