name: Test a reusable workflow and an action to read and write files 
on:
  workflow_dispatch
jobs:   
  job1: 
    name: read and write files using reusable workflow
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/read_write_files.yml@main
    with:
      json_file_path: .github/test-files/f1.json
      yaml_file_path: .github/test-files/f1.yml
      
      
  
         
