name: Test a reusable workflow to read a json file 
on:
  workflow_dispatch
jobs:   
  job1: 
    name: call the reusable workflow
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/read_json_file.yml@main
    with:
      json_file_path: .github/test-files/f1.json
  job2: 
    name: read output from another job
    runs-on: ubuntu-latest
    needs: job1
    env:
      jsondata: ${{needs.job1.outputs.jsondata}} 
    steps:
      - name: log output
        run: | 
          echo ${{env.jsondata}}
          echo ${{env.jsondata.level0.level1.level2.level3.level4.list[1]}}
      #  echo yamldata=${{steps.read_yaml.outputs.result}} >> GITHUB_ENV
      #  echo ${{yamldata.level0.level1.level2.level3.level4.list}}
      
      
  
         
