name: Test a reusable workflow and an action that use repo environment
on:
  workflow_dispatch
jobs:   
  job1:
    name: j1 call a reusable workflow
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/repo_environment.yml@main
  job2:
    name: j2 call an action 
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: call the action 
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/repo_environment@main
        with:
          repo_environment_var: ${{environment.name}}
