name: Test a reusable workflow and an action using a nested call to a shell script.
on:
  workflow_dispatch
env:
  pt: workflows-and-actions/reusable-workflows-and-actions
jobs:   
  job1:
    name: j1 call a reusable workflow
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/scripts_and_nested_calls.yml@main
    with:
      nested_workflow_file: nested_workflow.yml
      script_file: hello.sh
      # script_file: workflows-and-actions/reusable-workflows-and-actions/.github/scripts/hello.sh

  job2:
    name: j2 call an action 
    runs-on: ubuntu-latest
    steps:
      - name: call the action 
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/scripts_and_nested_calls@main
        with:
          script_file: hello.sh # the script has to be in the .github/scripts directory of the called action
