name: Test a reusable workflow and an action using nested calls and shell script files
on:
  workflow_dispatch
env:
  pt: workflows-and-actions/reusable-workflows-and-actions
jobs:   
  job0:
    name: set paths
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/set_paths.yml@main
  job1:
    name: j1 call a reusable workflow
    needs: job0
    uses: ${{ needs.job0.outputs.path1 }}
    # uses: "${{env.pt}}/.github/workflows/scripts_and_nested_calls.yml@main"
    with:
      nested_workflow_file: nested_workflow.yml
      script_file: hello.sh
  job2:
    name: j2 call an action 
    runs-on: ubuntu-latest
    steps:
      - name: call the action 
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/scripts_and_nested_calls@main
        with:
          script_file: hello.sh
