# We must pass secrets to reusable workflows and actions, variables are passed by default to workflows but not to actions.
name: Test reusable workflow and action with secrets and variables
on:
  workflow_dispatch
jobs:
  job1:
    name: j1 Test secrets_and_vars reusable workflow 
    uses: workflows-and-actions/reusable-workflows-and-actions/.github/workflows/secrets_and_vars.yml@main
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s: ${{ secrets.repo_secret }}       
      org_s: ${{ secrets.org_secret }}    
  job2:
    name: j2 Test secrets_and_vars action
    runs-on: ubuntu-latest
    steps:
      - name: call the action in this step
        id: get_output
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/secrets_and_vars@main
        with: # we cannot really pass secrets to an action, passing as inputs not a good idea, only doing it for demo
          repo_s: ${{ secrets.repo_secret }}       
          org_s: ${{ secrets.org_secret }}
          repo_v: ${{ secrets.repo_var }}       
          org_v: ${{ secrets.org_var }}  
      - run: echo test done
        
  job3:
    name: j3 print secrets and variables in the caller workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{secrets.env_dev_secret}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      - run: echo ${{secrets.org_secret}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      - run: echo ${{secrets.ORG_SECRET}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      - run: echo ${{vars.repo_var}} # a variable defined at the repository level
      - run: echo ${{vars.org_var}} # a variable defined at the organization level
      - run: echo test done.
      
